version: '3'

services:
  vpn-gateway:
    container_name: vpn-gw
    image: strongswan/strongswan:latest
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./ipsec.conf:/etc/ipsec.conf
      - ./ipsec.secrets:/etc/ipsec.secrets
    networks:
      vpn-network:
        ipv4_address: 192.168.1.1
      local-network:
        ipv4_address: 192.168.2.1
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  frr-router:
    container_name: frr-router
    image: frrouting/frr:latest
    depends_on:
      - vpn-gateway
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./frr.conf:/etc/frr/frr.conf
      - ./daemons:/etc/frr/daemons
    networks:
      vpn-network:
        ipv4_address: 192.168.1.2
      local-network:
        ipv4_address: 192.168.2.2
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  local-host:
    container_name: local-host
    image: alpine:latest
    depends_on:
      - frr-router
    command: sh -c "ip route add 10.0.0.0/16 via 192.168.2.2 && sleep infinity"
    cap_add:
      - NET_ADMIN
    networks:
      local-network:
        ipv4_address: 192.168.2.10
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped

networks:
  vpn-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
  local-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24 