services:
  router1:
    container_name: router1
    build: .
    image: frr-router
    restart: unless-stopped
    networks:
      bgp_net:
        ipv4_address: 172.30.0.10
    volumes:
      - ./frr-configs/router1/:/etc/frr/
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: >
      -c "
        ip addr add 1.1.1.1/32 dev lo &&
        chown -R frr:frr /etc/frr &&
        chmod 644 /etc/frr/*.conf &&
        chmod 755 /etc/frr &&
        mkdir -p /var/run/frr &&
        chown -R frr:frr /var/run/frr &&
        /usr/lib/frr/frrinit.sh start &&
        tail -f /dev/null
      "

  router2:
    container_name: router2
    build: .
    image: frr-router
    restart: unless-stopped
    networks:
      bgp_net:
        ipv4_address: 172.30.0.2
    volumes:
      - ./frr-configs/router2/:/etc/frr/
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: >
      -c "
        ip addr add 2.2.2.2/32 dev lo &&
        chown -R frr:frr /etc/frr &&
        chmod 644 /etc/frr/*.conf &&
        chmod 755 /etc/frr &&
        mkdir -p /var/run/frr &&
        chown -R frr:frr /var/run/frr &&
        /usr/lib/frr/frrinit.sh start &&
        tail -f /dev/null
      "

  router3:
    container_name: router3
    build: .
    image: frr-router
    restart: unless-stopped
    networks:
      bgp_net:
        ipv4_address: 172.30.0.3
    volumes:
      - ./frr-configs/router3/:/etc/frr/
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: >
      -c "
        ip addr add 3.3.3.3/32 dev lo &&
        chown -R frr:frr /etc/frr &&
        chmod 644 /etc/frr/*.conf &&
        chmod 755 /etc/frr &&
        mkdir -p /var/run/frr &&
        chown -R frr:frr /var/run/frr &&
        /usr/lib/frr/frrinit.sh start &&
        tail -f /dev/null
      "

  router4:
    container_name: router4
    build: .
    image: frr-router
    restart: unless-stopped
    networks:
      bgp_net:
        ipv4_address: 172.30.0.4
    volumes:
      - ./frr-configs/router4/:/etc/frr/
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: >
      -c "
        ip addr add 4.4.4.4/32 dev lo &&
        chown -R frr:frr /etc/frr &&
        chmod 644 /etc/frr/*.conf &&
        chmod 755 /etc/frr &&
        mkdir -p /var/run/frr &&
        chown -R frr:frr /var/run/frr &&
        /usr/lib/frr/frrinit.sh start &&
        tail -f /dev/null
      "

networks:
  bgp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24 